### ISSUE TITLE
AgeFilter and blacklisting are not being removed

### ISSUE THREAD

**Issue by royere** [Netflix/repokid#16]
Hello,
Once you set an agefilter or a blacklistfilter, the account is tagged in this way in the repokid display_role_cache. Even if you remove the agefilter (to 0 or 1) or remove the blacklistfilter, the account stays tagged. Even if you repokid update :

aardvark              [u'AgeFilter']        False                 0                     0                     Never                 []
admin                 [u'BlacklistFilter']  False                 0                     0                     Never                 []

Config.json view: 
   "filter_config": {
        "AgeFilter": {
            "minimum_age": 0
        }, 
        "BlacklistFilter": {
            "all": []
        }

**Comment by mcpeak** [comment]
I just merged a fix that should address this.  Thanks for reporting and let me know if you see any similar issues.  I'm also trying to come up with a unit testing strategy to catch stuff like this in the future.
