### ISSUE TITLE
Repo-ing a role "would not" repo

### ISSUE THREAD

**Issue by royere** [Netflix/repokid#17]
I have the correct permissions in place, but when I repo a role I have an information that repokid would do it, but in fact it would not :)

`(repokid)[ec2-user@ip-172-31-42-155 repokid]$ repokid repo_role 840221307699 GatedGardenAudit
Loaded config from /home/ec2-user/repokid/config.json
2017-06-23 09:00:08,024 INFO: Would delete policy from GatedGardenAudit with name GatedGardenPolicy [in /home/ec2-user/repokid/repokid/repokid.py:595]`

Logs of repokid show no information, nor in cloudtrail logs.

**Comment by mcpeak** [comment]
You have to run it in commit mode for it to actually make a change.  The call should be:

`repokid repo_role 840221307699 GatedGardenAudit -c`

If this doesn't work please let me know.  Also if you think this isn't clear I can update the documentation.

**Comment by mcpeak** [comment]
Sorry, clicked close by accident.  @royere please let me know if this addresses your issue.

**Comment by royere** [comment]
I just tried again with -c and without, below is the extract of the display_role_cache
`testaardvark1         []                    True                  47                    47                    Never                 [u'acm', u'config',…`
When I try to remove it : 
`(repokid)[ec2-user@ip-172-31-42-155 repokid]$ repokid repo_role 84022130769 testaardvark1 -c
Loaded config from /home/ec2-user/repokid/config.json
2017-06-29 08:49:13,837 WARNING: Could not find role with name testaardvark1 [in /home/ec2-user/repokid/repokid/repokid.py:567]
(repokid)[ec2-user@ip-172-31-42-155 repokid]$ repokid repo_role 84022130769 testaardvark1 
Loaded config from /home/ec2-user/repokid/config.json
2017-06-29 08:49:55,050 WARNING: Could not find role with name testaardvark1 [in /home/ec2-user/repokid/repokid/repokid.py:567]
(repokid)[ec2-user@ip-172-31-42-155 repokid]$ `

**Comment by royere** [comment]
I updated with a git pull first and python setup.py develop first :) of course.

**Comment by mcpeak** [comment]
Hmm, that's really interesting.  Do you have other roles in the account you can try?  Also what's the output of `repokid display_role 84022130769 testaardvark1`?

**Comment by mcpeak** [comment]
@royere is this still an issue?

**Comment by royere** [comment]
I haven't been able to solve it, so I am testing on another platform which doesn't have the issue. Please close the issue, yes :)
