### ISSUE TITLE
Suggestion: Continue to cut releases instead of pulling from master branch

### ISSUE THREAD

**Issue by kmcquade** [Netflix/repokid#243]
It would be great if Repokid and Aardvark continued to have regular releases. Recently ran into an issue where my Terraform module for Repokid and Aardvark broke because of the updates to Python3 from Python2.7 (not production, so all good). If I could have pulled from a release tag instead of the master branch, that situation could have been avoided. Just a suggestion.

FYI - @mcpeak

**Comment by mcpeak** [comment]
Hi @kmcquade great point, I will ensure we do so in the future. cc @castrapel.

**Comment by patricksanders** [comment]
Hey @kmcquade, per your request I created a release before merging some logging changes. We'll be sure to continue to do this. Thanks for the suggestion.
