### ISSUE TITLE
permission shown for all roles

### ISSUE THREAD

**Issue by citicruiser** [Netflix/repokid#245]
I installed and configured aardvark and repokid on the same VM and they ran successfully without error.  However when I ran 'repokid display_role_cache 1234567', it came back with 0 permission for all roles.

I just pick a specific role pei-test for exam and below are some troubleshooting steps I did:

1. curl localhost:5000/api/1/advisors?arn=arn:aws:iam::12344567:role/pei-test
{"arn:aws:iam::1234567:role/pei-test":[{"lastAuthenticated":0,"lastAuthenticatedEntity":null,"lastUpdated":"Sat, 11 Jan 2020 21:28:22 GMT","serviceName":"Amazon Elastic Container Service for Kubernetes","serviceNamespace":"eks","totalAuthenticatedEntities":0}],"count":1,"page":1,"total":1}

2. repokid find_roles_with_permissions  "eks:ListFargateProfiles"
Loaded config from /opt/src/repokid/config.json
2020-01-11 21:34:35,252 INFO: ARN arn:aws:iam::1234567:role/pei-test has ['eks:listfargateprofiles'] [in /opt/src/repokid/repokid/cli/repokid_cli.py:604]
ARN arn:aws:iam::1234567:role/pei-test has ['eks:listfargateprofiles']

It seems the permission of eks:listfargateprofiles is in the role pei-test, I don't understand why it does not show up in repokid display_role_cache?

best,

pei

**Comment by patricksanders** [comment]
Hey @citicruiser, are you still having issues with this? If so, could you provide any more information that might help me replicate this problem?

**Comment by patricksanders** [comment]
Closing as stale, please open a new issue if necessary.
