### ISSUE TITLE
Add Flake8 to TravisCI

### ISSUE THREAD

**Issue by mcpeak** [Netflix/repokid#43]
It would be nice to have TravisCI check flake8 for the project.  We can ignore the finding about lines longer than 80 (line length limit should be 120).

**Comment by suprithIUB** [comment]
@mcpeak we can add line length limit by adding a new file setup.cfg, in the repository main dir, containing length restrictions. Let me know.

**Comment by mcpeak** [comment]
@suprithIUB I like it, let's do it 👍
