### ISSUE TITLE
ARN not found in Access Advisor

### ISSUE THREAD

**Issue by mojhrepo** [Netflix/repokid#67]
Hi 
I've deployed Aardvark and Repokid to a single EC2 instance. 
Aaardvark updates ok from a target account and I can see the expected data in two tables in the Aardvark DB.
Repokid updates and displays its cache successfully from the Aardvarl api.

However when I try and display a single role or repo a role (any role) I get "WARNING: ARN not found in Access Advisor"

[root@ip-10-0-10-244 bin]#
[root@ip-10-0-10-244 bin]# ./repokid update_role_cache 123456789000
Loaded config from /usr/local/bin/config.json
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): dynamodb.eu-west-1.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.amazonaws.com
2018-02-15 09:31:56,558 INFO: Updating role data for account 123456789000 [in /root/gitrepo/repokid/repokid/cli/repokid_cli.py:403]
INFO:repokid:Updating role data for account 123456789000
 38%|¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦?                                                                                                                    | 27/72 [00:07<00:12,  3.66it/s]INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): iam.amazonaws.com
100%|¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 72/72 [00:20<00:00,  3.47it/s]
2018-02-15 09:32:17,303 INFO: Finding inactive accounts [in /root/gitrepo/repokid/repokid/cli/repokid_cli.py:410]
INFO:repokid:Finding inactive accounts
2018-02-15 09:32:17,328 INFO: Filtering roles [in /root/gitrepo/repokid/repokid/cli/repokid_cli.py:413]
INFO:repokid:Filtering roles
2018-02-15 09:32:17,331 INFO: Loaded plugin repokid.filters.age:AgeFilter [in /root/gitrepo/repokid/repokid/cli/repokid_cli.py:360]
INFO:repokid:Loaded plugin repokid.filters.age:AgeFilter
2018-02-15 09:32:17,332 INFO: Loaded plugin repokid.filters.lambda:LambdaFilter [in /root/gitrepo/repokid/repokid/cli/repokid_cli.py:360]
INFO:repokid:Loaded plugin repokid.filters.lambda:LambdaFilter
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
2018-02-15 09:32:17,729 ERROR: S3 blacklist config was set but unable to connect retrieve object, quitting [in /root/gitrepo/repokid/repokid/filters/blacklist/__init__.py:24]
ERROR:repokid:S3 blacklist config was set but unable to connect retrieve object, quitting

[root@ip-10-0-10-244 bin]# ./repokid display_role_cache 123456789000
Loaded config from /usr/local/bin/config.json
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): dynamodb.eu-west-1.amazonaws.com
100%|¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 73/73 [00:00<00:00, 203.17it/s]

[root@ip-10-0-10-244 bin]# ./repokid display_role 123456789000 RepokidTest
Loaded config from /usr/local/bin/config.json
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): dynamodb.eu-west-1.amazonaws.com

Role repo data:
Name         Refreshed                   Disqualified By    Can be repoed      Permissions    Repoable  Repoed      Services
-----------  --------------------------  -----------------  ---------------  -------------  ----------  --------  ----------
RepokidTest  2018-02-15T09:40:33.653533  []                 True                         0           0  Never              0

Policy history:
  Number  Source    Discovered                    Permissions  Services
--------  --------  --------------------------  -------------  ----------
       0  Scan      2018-02-14T15:59:56.471492              2  [u's3']

Stats:
Date    Event Type    Permissions Count    Disqualified By
------  ------------  -------------------  -----------------

2018-02-15 09:41:39,767 WARNING: ARN not found in Access Advisor: arn:aws:iam::123456789000:role/RepokidTest [in /root/gitrepo/repokid/repokid/cli/repokid_cli.py:576]
WARNING:repokid:ARN not found in Access Advisor: arn:aws:iam::123456789000:role/RepokidTest

[root@ip-10-0-10-244 bin]# ./repokid repo_role 123456789000 RepokidTest
Loaded config from /usr/local/bin/config.json
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sts.amazonaws.com
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): dynamodb.eu-west-1.amazonaws.com
2018-02-15 09:42:16,874 WARNING: ARN not found in Access Advisor: None [in /root/gitrepo/repokid/repokid/cli/repokid_cli.py:668]
WARNING:repokid:ARN not found in Access Advisor: None
[root@ip-10-0-10-244 bin]#

I deployed Repokid to an alternative instance and connected back to the Aardvark api successfully but still have the same issue with role display and repo.

Any ideas?

Thanks

**Comment by mcpeak** [comment]
@mojhrepo it looks like you're stuck on an invalidly configured blacklist object:

`2018-02-15 09:32:17,729 ERROR: S3 blacklist config was set but unable to connect retrieve object, quitting [in /root/gitrepo/repokid/repokid/filters/blacklist/init.py:24]`

**Comment by mcpeak** [comment]
If this is the problem the instructions could probably use updating.  Please confirm if this is the case.

**Comment by mojhrepo** [comment]
Yes, my fault. Ignored Blacklist error as initially read as optional config.
As filter was active in develop install it needed a config.
Re-read the optional config / active filters sections and it became clear.
Removed blacklist from active filter list and all good.
Thanks

**Comment by mcpeak** [comment]
Thank you 👍

**Comment by jonnieb007** [comment]
It would be great if the instructions where updated to remove blocklist wrt S3 (see below) from config.json 

"BlocklistFilter": {
            "all": [],
            "blocklist_bucket": {
                "account_number": "<S3_blocklist_account>",
                "assume_role": "<S3_blocklist_assume_role>",
                "bucket": "<BLOCKLIST_BUCKET>",
                "key": "<PATH/blocklist.json>",
                "region": "<S3_blocklist_region"
            }
        },
