### ISSUE TITLE
Support Sid based exclusion

### ISSUE THREAD

**Issue by mcpeak** [Netflix/repokid#70]
We could use Sid's with a certain prefix (something like `RKIGNORE`) to exclude statements from repoing.  This would allow us to preserve some parts of an inline policy without excluding the entire role from repo.

In order to support this we need to:

- create a new option in config: something like sid_ignore_prefix
- add the sid_ignore_prefix check in the right places.  We still want to see these statements and store them for rolling back and searching perms but we want to exclude permissions that are included in these statements when making policy suggestions and performing repo.

Some functions that are going to need to change:
 - _get_repoed_policy, _get_role_permissions, _get_permissions_in_policy

This is a decent amount of work so we're going to want to make sure we're rock solid here by adding tests, etc.  Finally we'll need to update the documentation to describe this new option.

**Comment by monkeysecurity** [comment]
This was fixed in #219
